### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by ThatFinn** [Siuolplex/DoorsOfInfinity#3]
EDIT: I did something wrong

**Comment by Finnlikecookies** [comment]
Error:
`[15:59:48] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "java.lang.ref.WeakReference.get()" because "me.benfah.doorsofinfinity.utils.MCUtils.mcServerReference" is null
	at me.benfah.doorsofinfinity.utils.MCUtils.getServer(MCUtils.java:10) ~[doorsofinfinity-2.0.0-modified.jar:?]
	at me.benfah.doorsofinfinity.dimension.InfinityDimHelper.getPersonalDimension(InfinityDimHelper.java:38) ~[doorsofinfinity-2.0.0-modified.jar:?]
	at me.benfah.doorsofinfinity.dimension.InfinityDimHelper.fromNbt(InfinityDimHelper.java:66) ~[doorsofinfinity-2.0.0-modified.jar:?]
	at me.benfah.doorsofinfinity.block.entity.InfinityDoorBlockEntity.method_11014(InfinityDoorBlockEntity.java:111) ~[doorsofinfinity-2.0.0-modified.jar:?]
	at net.minecraft.class_2818.method_31716(class_2818.java:463) ~[client-intermediary.jar:?]
	at net.minecraft.class_6603.method_38593(class_6603.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_6603.method_38588(class_6603.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_12224(class_2818.java:458) ~[client-intermediary.jar:?]
	at qouteall.imm_ptl.core.chunk_loading.MyClientChunkManager.method_16020(MyClientChunkManager.java:123) ~[imm_ptl_core-2.3.1-94bc3db1d1e1fb5d.jar:?]
	at net.minecraft.class_634.method_38539(class_634.java:709) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11128(class_634.java:704) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.method_11528(class_2672.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.method_11054(class_2672.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at qouteall.imm_ptl.core.ClientWorldLoader.lambda$withSwitchedWorld$11(ClientWorldLoader.java:492) ~[imm_ptl_core-2.3.1-94bc3db1d1e1fb5d.jar:?]
	at qouteall.imm_ptl.core.ClientWorldLoader.withSwitchedWorld(ClientWorldLoader.java:474) ~[imm_ptl_core-2.3.1-94bc3db1d1e1fb5d.jar:?]
	at qouteall.imm_ptl.core.ClientWorldLoader.withSwitchedWorld(ClientWorldLoader.java:491) ~[imm_ptl_core-2.3.1-94bc3db1d1e1fb5d.jar:?]
	at net.minecraft.class_310.md148ecc$imm_ptl_core$lambda$onCreateTask$0$2(class_310.java:8977) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1129) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[15:59:50] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "java.lang.ref.WeakReference.get()" because "me.benfah.doorsofinfinity.utils.MCUtils.mcServerReference" is null
	at me.benfah.doorsofinfinity.utils.MCUtils.getServer(MCUtils.java:10) ~[doorsofinfinity-2.0.0-modified.jar:?]
	at me.benfah.doorsofinfinity.dimension.InfinityDimHelper.getPersonalDimension(InfinityDimHelper.java:38) ~[doorsofinfinity-2.0.0-modified.jar:?]
	at me.benfah.doorsofinfinity.dimension.InfinityDimHelper.fromNbt(InfinityDimHelper.java:66) ~[doorsofinfinity-2.0.0-modified.jar:?]
	at me.benfah.doorsofinfinity.block.entity.InfinityDoorBlockEntity.method_11014(InfinityDoorBlockEntity.java:111) ~[doorsofinfinity-2.0.0-modified.jar:?]
	at net.minecraft.class_2818.method_31716(class_2818.java:463) ~[client-intermediary.jar:?]
	at net.minecraft.class_6603.method_38593(class_6603.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_6603.method_38588(class_6603.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_12224(class_2818.java:458) ~[client-intermediary.jar:?]
	at qouteall.imm_ptl.core.chunk_loading.MyClientChunkManager.method_16020(MyClientChunkManager.java:123) ~[imm_ptl_core-2.3.1-94bc3db1d1e1fb5d.jar:?]
	at net.minecraft.class_634.method_38539(class_634.java:709) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11128(class_634.java:704) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.method_11528(class_2672.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.method_11054(class_2672.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at qouteall.imm_ptl.core.ClientWorldLoader.lambda$withSwitchedWorld$11(ClientWorldLoader.java:492) ~[imm_ptl_core-2.3.1-94bc3db1d1e1fb5d.jar:?]
	at qouteall.imm_ptl.core.ClientWorldLoader.withSwitchedWorld(ClientWorldLoader.java:474) ~[imm_ptl_core-2.3.1-94bc3db1d1e1fb5d.jar:?]
	at qouteall.imm_ptl.core.ClientWorldLoader.withSwitchedWorld(ClientWorldLoader.java:491) ~[imm_ptl_core-2.3.1-94bc3db1d1e1fb5d.jar:?]
	at net.minecraft.class_310.md148ecc$imm_ptl_core$lambda$onCreateTask$0$2(class_310.java:8977) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1129) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`
